### ISSUE TITLE
Certain Resolutions Cause `tokio-runtime-worker` Panic

### ISSUE THREAD

**Issue by Liamazing** [livekit/python-sdks#119]
Running the `publish_hue.py` example with `WIDTH, HEIGHT = 2560, 1920` or `WIDTH, HEIGHT = 5120, 960` results in participant joining the room but without publishing the hue video. The behavior is accompanied by the following output:
```
INFO:root:connected to room my-room
thread 'tokio-runtime-worker' panicked at livekit/src/room/options.rs:184:5:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Larger resolutions, such as 4K UHD `WIDTH, HEIGHT = 3840, 2160` work fine.

Reproduce by running the `publish_hue` example from inside the following Dockerfile:
```
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y curl python3.9-dev=3.9.5-3* python3-pip
RUN curl -sSL https://get.livekit.io | bash
RUN python3.9 -m pip install --upgrade pip
RUN python3.9 -m pip install livekit==0.6.0 livekit-api==0.3.0 numpy opencv-python-headless
```

**Comment by theomonnom** [comment]
This will be fixed on the next release

**Comment by theomonnom** [comment]
You can already try 0.7.0.dev1
