### ISSUE TITLE
FPS limiter

### ISSUE THREAD

**Issue by sergeevii123** [livekit/python-sdks#175]
Hi, is it possible to add FPS limiter to livekit?

so 
```
async def receive_frames(stream: rtc.VideoStream):
        async for frame in video_stream:
            # received a video frame from the track, process it here
            pass
```
will actually give frames with FPS x

**Comment by davidzhao** [comment]
This would be handled in your application logic. if you want say 5 FPS, you would just drop frames until it's been ~200ms since the last frame processed.
