### ISSUE TITLE
Room._listen_task is not cancelled when server closes room

### ISSUE THREAD

**Issue by gigaverse-oz** [livekit/python-sdks#199]
# Issue Description

## Overview

When the Livekit Server terminates a room and removes a Python client, the task responsible for listening (`self._listen_task`) does not properly conclude or cancel.

## Background

We have set up a Python participant to join a specific room and listen to a particular track. If the track is no longer published, the Python participant leaves the room, completes all asynchronous tasks, and then the process exits. However, if the room is deleted, the Python participant struggles to disconnect and the `_listen_task` remains active.

## Diagnostics

The `Room.disconnect()` method is designed to clear the task queue and wait for `self._task` to finish. But, if the Livekit Server deletes the room, the `Room.disconnect()` cannot complete as it fails the `self.isconnected()` check, resulting in `self._task` remaining in a running state.

```python
if not self.isconnected():
            return
```

View the code segment here: [Room.py Line 221](https://github.com/livekit/python-sdks/blob/7383150da25cf92c4b31b3d2847a7d8eae704b63/livekit-rtc/livekit/rtc/room.py#L221)

## Requested Solution

We suggest introducing an `aclose()` function to manage disconnections and clean up any remaining asynchronous tasks. Currently, we have implemented the following in the object that utilizes the Room object:

```python
    async def aclose(self):
        if self.is_closed():
            return
        try:
            for task in self._tasks:
                task.cancel()
            await asyncio.gather(*self._tasks, return_exceptions=True)
            await self._room.disconnect()
        except Exception as err:
            logger.error(f"Error shutting down transcript agent: {str(err)}")
        finally:
            if self._room._task:
                self._room._task.cancel()
                logger.warning("Room disconnect method failed to close _listen_task")
            self._closed = True
```

**Comment by theomonnom** [comment]
The correct implementation would be to always call self._room.disconnect like you do, the difference is that we're now awaiting the main task in https://github.com/livekit/python-sdks/pull/200. There is no need to cancel because the Rust SDK should send EOS which will break the infinite loop

**Comment by theomonnom** [comment]
I'm going to verify that is https://github.com/livekit/rust-sdks/blob/ea0bc40093ebcc7d308b2c4e8d088340557bdf46/livekit-ffi/src/server/room.rs#L566 is correctly ran if the disconnect comes from the server

**Comment by gigaverse-oz** [comment]
Thanks for the quick reply and fix. Will also verify once merged :)

**Comment by b4stien** [comment]
The associated PR was never merged. I'm experiencing some issues with the Python SDK resembling this. Did you have other plan to fix that? Have they been implemented?
