### ISSUE TITLE
Missing property `attributes` in AccessToken class

### ISSUE THREAD

**Issue by albertpurnama** [livekit/python-sdks#232]
Reference to NodeJS counterpart:
https://github.com/livekit/node-sdks/blob/720208f64dbcd76c1c8e23177692ebfcb7f0cdfb/packages/livekit-server-sdk/src/AccessToken.ts#L123

I'm looking to use Python's client SDK but I was unable to because attributes does not exist in python's AccessToken.

**Comment by davidzhao** [comment]
Oops, we missed this. Fixed in #233

**Comment by keepingitneil** [comment]
Released as livekit-api v0.7.0: https://pypi.org/project/livekit-api/

**Comment by albertpurnama** [comment]
Awesome work team @davidzhao @keepingitneil
