### ISSUE TITLE
How to receive data messages in Python AI Agent?

### ISSUE THREAD

**Issue by albertcyhe** [livekit/python-sdks#313]
### Context
I'm developing an AI Agent using the LiveKit Python SDK. I need to receive data messages from an iOS client that sends context information including current and previous sentences.

### Current Implementation (iOS Client)
The iOS client sends data using `publishData`:

```swift
try await room.localParticipant?.publishData(
    data: jsonData,
    topic: contextTopic,
    options: DataPublishOptions()
)
```

### Question
1. What is the correct way to receive these data messages in a Python AI Agent?
2. I've looked through the documentation but couldn't find a clear method for receiving data messages in the Agents framework.
3. Is there an official way to handle data messages in LiveKit Python Agents, similar to how we can send data using `RoomService.send_data`?

### Documentation References
- I've checked the Python SDK documentation at https://docs.livekit.io/python/livekit/api/
- I can see `RoomService.send_data` but no clear method for receiving data

### Additional Information
- Using LiveKit Python SDK
- Implementing an AI Agent
- Need to receive JSON data containing context information

Would appreciate any guidance on the recommended approach for handling data messages in Python AI Agents.

**Comment by albertcyhe** [comment]
Finished, I reviewed document and source code.

**Comment by xianqiliu** [comment]
@albertcyhe could you please tell me how to receive? i can't find a way to do that. thank you in advanced
